### ISSUE TITLE
Texture bugs with Cyrillic version of Minecraft Ten

### ISSUE THREAD

**Issue by ForestVL** [ewanhowell5195/MinecraftTitleGenerator#68] opened 2023-06-24 01:33 UTC
If you create Minecraft title with these parameters:
— Minecraft Ten (Cyrillic)
— Gradient texture
Title appeares with white stripes

![minecraft_title (4)](https://github.com/ewanhowell5195/MinecraftTitleGenerator/assets/136828797/257aecb1-d4ec-448b-a05a-f910b8f09514)
![дцуйф](https://github.com/ewanhowell5195/MinecraftTitleGenerator/assets/136828797/c7e0d32e-d0f9-41d5-80a2-714181af3d4a)

**Comment by ForestVL** [comment] 2023-06-26 16:37
[Here's the preset file](https://drive.google.com/file/d/12pcqoq2886yiXW7fWIHCnr3djfjFUshv/view?usp=drivesdk) 

BUT, I actually investigated a little more and noticed that white stripes only appear in mobile web app. On PC app everything works fine. Perhaps this is why you weren't able to reproduce.

**Comment by ewanhowell5195** [comment] 2023-06-26 18:00
unable to reproduce on mobile or with the preset.

can you provide the operating system and version, and the browser and version that you are using

**Comment by ForestVL** [comment] 2023-06-27 02:43
Android 12; V2061 Build/SP1A.210812.003
Chrome 114.0.5735.131

**Comment by ewanhowell5195** [comment] 2023-06-27 08:32
closing as unable to reproduce

**Closed** 2023-06-27 08:32 UTC
